language: android
sudo: false

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-support
    - extra-android-m2repository
    
before_install:
  - chmod +x gradlew
    
script:
  - ./gradlew :app:assembleRelease
