language: android
sudo: false

android:
  components:
    - platform-tools
    - tools
    - extra-android-support
    - extra-android-m2repository
    
before_install:
  - chmod +x gradlew
    
script:
  - ./gradlew :app:assembleRelease
